### ISSUE TITLE
Testcontainer Document API

### ISSUE THREAD

**Issue by FRosner** [codecentric/serverless-astra-graalvm#11]
- https://stargate.io/docs/stargate/1.0/developers-guide/install/install_cass_40.html
- https://www.testcontainers.org/modules/databases/cassandra/

**Comment by rafaroca** [comment]
Stargate container in dev-mode apparently contains cassandra4.0.
✅ Test is starting a stargate container
✅ Test pokes the container on a port via Java HttpClient
🔲 Test uses DocumentAPI
