### ISSUE TITLE
Proper error handling/logging

### ISSUE THREAD

**Issue by luftigdev** [codecentric/serverless-astra-graalvm#14]
The LambdaHandler throws an exception when the POSTed order is not valid. Since the exception is never caught, the exception message never surfaces anywhere in the logs. The API Gateway returns 500 Server Error.

This should instead give the user a proper 400 code and a message what is wrong with the request.

**Comment by rafaroca** [comment]
@FRosner I am trying to return a LambdaResponse which fits to [the documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html). I cannot get far though, as my exception is not caught. The JVM seems to exit before the catch clause is executed at [LambdaHandler:62](https://github.com/codecentric/serverless-astra-graalvm/blob/main/src/main/java/com/github/codecentric/LambdaHandler.java#L62). Do you have any clue why there is no log output from the logger inside the catch? I can't fathom why there's nothing in CloudWatch. Every RuntimeException should hit the catch clause, right?

**Comment by rafaroca** [comment]
After reading the CloudWatch output once again, it became clear: `Task timed out after 3.00 seconds`. Well, there's my problem. Increasing the timeout to 30s, it reveals a proper error message.

**Comment by rafaroca** [comment]
There is a generic 400 error message now. I'd leave it for this. If you would rather have a fully fledged verification of the Order, then we can open another ticket :)

**Comment by FRosner** [comment]
Thanks @rafaroca!
